Repository starfederation/datastar, pull requests merged in 2025-02, with the labels that each got.

#561 Use `retry` in SSE output examples instead of `retryDuration`
  sdk/README.md
Labels: documentation

#555 Bundler aliasing
  CHANGELOG.md
  README.md
  build/run.go
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar-core.js
  bundles/datastar-core.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/bundles/datastar-aliased.ts
  library/src/engine/engine.ts
  library/src/engine/types.ts
  library/src/plugins/official/core/attributes/signals.ts
  library/src/plugins/official/dom/attributes/on.ts
  library/src/utils/text.ts
  sdk/go/consts.go
  site/routes_bundler.go
  site/routes_bundler.qtpl
  site/routes_bundler.templ
  site/routes_examples.go
  site/shared.templ
  site/smoketests/animations_test.go
  site/smoketests/dialogs_browser_test.go
  site/smoketests/sortable_test.go
  site/static/md/examples/aliased_data_attributes.md
  site/static/md/reference/javascript_api.md
Labels: enhancement

#573 Update SDKs to ignore `retry` if set to default
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/backend/actions/sse.ts
  sdk/README.md
  sdk/go/consts.go
  sdk/go/sse.go
  sdk/php/src/ServerSentEventGenerator.php
  sdk/test/get-cases/executeScriptWithDefaults/output.txt
  sdk/test/get-cases/executeScriptWithMultilineScript/output.txt
  sdk/test/get-cases/executeScriptWithoutDefaults/output.txt
  sdk/test/get-cases/mergeFragmentsWithDefaults/output.txt
  sdk/test/get-cases/mergeFragmentsWithMultilineFragments/output.txt
  sdk/test/get-cases/mergeFragmentsWithoutDefaults/output.txt
  sdk/test/get-cases/mergeSignalsWithDefaults/output.txt
  sdk/test/get-cases/mergeSignalsWithMultilineSignals/output.txt
  sdk/test/get-cases/mergeSignalsWithoutDefaults/output.txt
  sdk/test/get-cases/removeFragmentsWithDefaults/output.txt
  sdk/test/get-cases/removeFragmentsWithoutDefaults/output.txt
  sdk/test/get-cases/removeSignalsWithDefaults/output.txt
  sdk/test/get-cases/sendTwoEvents/output.txt
  sdk/test/post-cases/readSignalsFromBody/output.txt
  site/static/md/reference/sdks.md
Labels: sdk

#575 Fix overflow issues and add menus (#567)
  site/routes_examples_active_search.templ
  site/routes_examples_bulk_update.templ
  site/routes_examples_click_to_load.templ
  site/routes_examples_dbmon.templ
  site/routes_examples_delete_row.templ
  site/routes_examples_edit_row.templ
  site/routes_examples_infinite_scroll.templ
  site/routes_examples_lazy_tabs.templ
  site/routes_examples_redirects.templ
  site/shared.templ
  site/static/md/examples/signals_changed.md
Labels: website

#522 Add search to the website
  .gitignore
  go.mod
  go.sum
  site/cmd/site/main.go
  site/router.go
  site/routes_home.go
  site/shared.templ
  site/shared_partials.go
  site/src/css/site.css
Labels: documentation

#585 Add dispatched `retrying` event
  library/src/plugins/official/backend/actions/sse.ts
  library/src/plugins/official/backend/shared.ts
Labels: enhancement

#601 Accomodate Zig SDK and examples to test runner changes
  examples/zig/httpz/hello-world/build.zig.zon
  examples/zig/tokamak/hello-world/build.zig.zon
  sdk/zig/httpz/build.zig
  sdk/zig/httpz/build.zig.zon
  sdk/zig/httpz/src/root.zig
  sdk/zig/httpz/src/tests.zig
  sdk/zig/test_runner.zig
  sdk/zig/tokamak/build.zig
  sdk/zig/tokamak/build.zig.zon
  sdk/zig/tokamak/src/root.zig
  sdk/zig/tokamak/src/tests.zig
Labels: sdk

#608 Fix fragment morph
  README.md
  Taskfile.yml
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar-core.js
  bundles/datastar-core.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/engine/engine.ts
  library/src/engine/types.ts
  library/src/plugins/official/backend/watchers/mergeFragments.ts
  library/src/vendored/idiomorph.esm.d.ts
  library/src/vendored/idiomorph.esm.js
  library/src/vendored/idiomorph.ts
  library/tsconfig.json
  sdk/go/consts.go
  site/router.go
  site/routes_examples.go
  site/routes_examples_merge_fragment.go
  site/routes_examples_merge_fragment.templ
  site/static/md/examples/merge_fragment.md
Labels: bug

#629 Observe DOM only after loading core plugins
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar-core.js
  bundles/datastar-core.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/engine/engine.ts
  sdk/go/consts.go
Labels: enhancement

#644 Remove cleanup function in `ref.ts`
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/dom/attributes/ref.ts
  sdk/go/consts.go
Labels: enhancement

#665 Fix remove fragment
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/backend/watchers/mergeFragments.ts
  library/src/plugins/official/backend/watchers/removeFragments.ts
  library/src/plugins/official/dom/attributes/on.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/routes_tests_merge_fragment.go
  site/routes_tests_merge_fragment.templ
  site/routes_tests_remove_fragment.go
  site/smoketests/key_casing_test.go
  site/smoketests/merge_fragment.go
  site/smoketests/merge_fragment_signal_test.go
  site/smoketests/on_load_test.go
  site/smoketests/ref_test.go
  site/smoketests/remove_fragment.go
  site/smoketests/setup_test.go
  site/smoketests/signals_change_path_test.go
  site/smoketests/signals_change_test.go
  site/static/md/tests/merge_fragment.md
  site/static/md/tests/remove_fragment.md
Labels: bug

#668 Update to Idiomorph 0.7.1
  CHANGELOG.md
  README.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/vendored/idiomorph.esm.js
  sdk/go/consts.go
  site/smoketests/merge_fragment_test.go
  site/smoketests/remove_fragment_test.go
Labels: enhancement

#678 Maintain whitespace in merged fragments
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/backend/actions/sse.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/routes_tests_merge_fragment_whitespace.go
  site/smoketests/merge_fragment_whitespace_test.go
  site/static/md/tests/merge_fragment_whitespace.md
Labels: enhancement

#624 feat(SDK): FastHTML SSE response and example (#576)
  examples/python/fasthtml/advanced.py
  examples/python/fasthtml/simple.py
  sdk/python/README.md
  sdk/python/pyproject.toml
  sdk/python/src/datastar_py/responses.py
Labels: sdk

#674 Add checkbox value behaviour based on signal type
  CHANGELOG.md
  README.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/plugins/official/dom/attributes/bind.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/smoketests/checkbox_input_array_test.go
  site/smoketests/checkbox_input_default_test.go
  site/smoketests/checkbox_input_string_test.go
  site/smoketests/radio_input_test.go
  site/smoketests/select_multiple_test.go
  site/smoketests/select_single_test.go
  site/smoketests/setup_test.go
  site/static/md/tests/checkbox_input_array.md
  site/static/md/tests/checkbox_input_default.md
  site/static/md/tests/checkbox_input_string.md
  site/static/md/tests/merge_fragment.md
  site/static/md/tests/merge_fragment_signal.md
  site/static/md/tests/radio_input.md
  site/static/md/tests/remove_fragment.md
  site/static/md/tests/select_multiple.md
  site/static/md/tests/select_single.md
  site/static/md/tests/signals_change.md
  site/static/md/tests/signals_change_path.md
Labels: enhancement

#687 Default to element value using `data-bind`
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar-core.js
  bundles/datastar-core.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/engine/signals.ts
  library/src/plugins/official/dom/attributes/bind.ts
  sdk/go/consts.go
  site/router.go
  site/routes_tests.go
  site/routes_tests_merge_fragment.go
  site/routes_tests_merge_fragment.templ
  site/routes_tests_merge_fragment_whitespace.go
  site/routes_tests_on_load.go
  site/smoketests/checkbox_input_checked_test.go
  site/smoketests/checkbox_input_string_test.go
  site/smoketests/checkbox_input_value_test.go
  site/smoketests/input_signal_test.go
  site/smoketests/input_value_test.go
  site/smoketests/on_load_test.go
  site/static/md/examples/indicator.md
  site/static/md/reference/attribute_plugins.md
  site/static/md/tests/checkbox_input_checked.md
  site/static/md/tests/checkbox_input_value.md
  site/static/md/tests/input_signal.md
  site/static/md/tests/input_value.md
  site/static/md/tests/merge_fragment_whitespace.md
  site/static/md/tests/on_load.md
Labels: enhancement

#689 Test command runs unit tests only
  .github/workflows/tests.yml
  Taskfile.yml
  site/smoketests/checkbox_input_array_test.go
  site/smoketests/checkbox_input_checked_test.go
  site/smoketests/checkbox_input_default_test.go
  site/smoketests/checkbox_input_value_test.go
  site/smoketests/input_signal_test.go
  site/smoketests/input_value_test.go
  site/smoketests/merge_fragment_signal_test.go
  site/smoketests/merge_fragment_test.go
  site/smoketests/merge_fragment_whitespace_test.go
  site/smoketests/on_load_test.go
  site/smoketests/remove_fragment_test.go
  site/smoketests/select_multiple_test.go
  site/smoketests/select_single_test.go
  site/static/md/tests/merge_fragment_whitespace.md
Labels: build, tests

#688 Update Idiomorph to 0.7.2
  CHANGELOG.md
  README.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/plugins/official/backend/attributes/indicator.ts
  library/src/plugins/official/backend/watchers/mergeFragments.ts
  library/src/vendored/idiomorph.esm.js
  sdk/go/consts.go
  site/routes_tests_merge_fragment_whitespace.go
  site/static/md/examples/indicator.md
Labels: enhancement

#691 Ensure plugins not reapplied
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar-core.js
  bundles/datastar-core.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/engine/engine.ts
  library/src/engine/types.ts
  library/src/plugins/official/dom/attributes/on.ts
  library/src/utils/dom.ts
  sdk/go/consts.go
Labels: enhancement
