Repository starfederation/datastar, pull requests merged in 2025-03, with the labels that each got.

#724 Fix checkbox array values
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/dom/attributes/bind.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/smoketests/checkbox_input_boolean_checked_test.go
  site/smoketests/checkbox_input_boolean_test.go
  site/smoketests/checkbox_input_checked_test.go
  site/smoketests/checkbox_input_value_checked_test.go
  site/static/md/tests/checkbox_input_array.md
  site/static/md/tests/checkbox_input_boolean.md
  site/static/md/tests/checkbox_input_boolean_checked.md
  site/static/md/tests/checkbox_input_default.md
  site/static/md/tests/checkbox_input_value.md
  site/static/md/tests/checkbox_input_value_checked.md
  site/static/md/tests/text_input_array.md
Labels: enhancement

#741 Allow a settle duration of `0` in Go SDK
  sdk/go/fragments.go
Labels: sdk

#746 Update Idiomorph to v0.7.3
  CHANGELOG.md
  README.md
  Taskfile.yml
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/vendored/idiomorph.esm.js
  sdk/go/consts.go
Labels: enhancement

#743 Delay applying plugins
  CHANGELOG.md
  README.md
  build/consts_datastar_readme.qtpl
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar-core.js
  bundles/datastar-core.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/engine/engine.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/smoketests/custom_plugin_test.go
  site/static/md/tests/custom_plugin.md
Labels: bug

#739 Add `getEventOutput()` method
  sdk/php/composer.json
  sdk/php/src/ServerSentEventGenerator.php
  sdk/php/src/events/EventInterface.php
  sdk/php/src/events/EventTrait.php
Labels: sdk

#748 Add exports for bundles and plugins
  library/package.json
  library/src/plugins/index.ts
Labels: enhancement

#750 Add custom build page to docs
  CHANGELOG.md
  site/routes_reference.go
  site/static/md/reference/custom_builds.md
Labels: documentation

#751 Improve signal match
  site/routes_errors_runtime.templ
Labels: documentation

#760 Fix recursive error in SSE requests
  README.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/plugins/official/backend/actions/sse.ts
  library/src/vendored/fetch-event-source.ts
  sdk/go/consts.go
Labels: bug

#761 Default to kebab-case and dispatch `datastar-sse` on element
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/backend/actions/sse.ts
  library/src/plugins/official/dom/attributes/class.ts
  library/src/plugins/official/dom/attributes/on.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/routes_tests_sse_events.go
  site/smoketests/sse_events_test.go
  site/static/md/reference/attribute_plugins.md
  site/static/md/tests/sse_events.md
Labels: enhancement

#771 Ignore keys with plugin names as prefixes
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar-core.js
  bundles/datastar-core.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/engine/engine.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/smoketests/plugin_name_prefix_test.go
  site/static/md/tests/plugin_name_prefix.md
Labels: enhancement

#772 Rename aliased bundle to `data-star-*`
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  library/src/bundles/datastar-aliased.ts
  site/routes_bundler.templ
  site/static/md/reference/attribute_plugins.md
  site/static/md/reference/custom_builds.md
  site/static/md/reference/overview.md
  site/static/md/tests/aliased.md
Labels: enhancement

#781 Fix merge fragments with multiple targets
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/backend/watchers/mergeFragments.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/routes_tests_merge_fragment_outer_multiple_targets.go
  site/static/md/tests/merge_fragment.md
  site/static/md/tests/merge_fragment_containing_on_event.md
  site/static/md/tests/merge_fragment_on_load.md
  site/static/md/tests/merge_fragment_outer_multiple_targets.md
  site/static/md/tests/merge_fragment_signals.md
  site/static/md/tests/merge_fragment_whitespace.md
Labels: bug

#786 Mark the target as a fragment merge target
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/backend/watchers/mergeFragments.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/routes_tests_merge_fragment_input_value.go
  site/smoketests/merge_fragment_input_value_test.go
  site/smoketests/setup_test.go
  site/static/md/tests/aliased.md
  site/static/md/tests/custom_plugin.md
  site/static/md/tests/merge_fragment.md
  site/static/md/tests/merge_fragment_containing_on_event.md
  site/static/md/tests/merge_fragment_input_value.md
  site/static/md/tests/merge_fragment_on_load.md
  site/static/md/tests/merge_fragment_outer_multiple_targets.md
  site/static/md/tests/merge_fragment_signals.md
  site/static/md/tests/merge_fragment_whitespace.md
  site/static/md/tests/on_load_delay.md
  site/static/md/tests/remove_fragment.md
  site/static/md/tests/sse_events.md
Labels: bug

#784 Delay removing event listener to next macrotask
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/backend/attributes/indicator.ts
  library/src/plugins/official/dom/attributes/on.ts
  sdk/go/consts.go
Labels: enhancement

#788 Remove ability to use key with `data-persist`
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/browser/attributes/persist.ts
  sdk/go/consts.go
  site/routes_errors_runtime.templ
  site/smoketests/persist_test.go
  site/static/md/examples/persist.md
  site/static/md/guide/getting_started.md
  site/static/md/reference/attribute_plugins.md
Labels: enhancement

#794 Trigger SSE error event after retries finished
  CHANGELOG.md
  README.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/README.md
  library/src/plugins/official/backend/actions/sse.ts
  library/src/plugins/official/backend/shared.ts
  library/src/vendored/fetch-event-source.ts
  sdk/go/consts.go
  site/routes_tests.go
  site/routes_tests_sse_error_event.go
  site/smoketests/sse_error_event_test.go
  site/static/md/reference/action_plugins.md
  site/static/md/tests/sse_error_event.md
  site/static/md/tests/sse_events.md
Labels: enhancement

#795 Add timing modifiers
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/browser/attributes/onIntersect.ts
  library/src/plugins/official/browser/attributes/onSignalChange.ts
  sdk/go/consts.go
  site/static/md/reference/attribute_plugins.md
Labels: enhancement

#770 Split various python SDK frameworks to different modules
  examples/python/django/ds/views.py
  examples/python/fastapi/app.py
  examples/python/fasthtml/advanced.py
  examples/python/fasthtml/simple.py
  examples/python/quart/app.py
  examples/python/sanic/app.py
  sdk/python/pyproject.toml
  sdk/python/src/datastar_py/django.py
  sdk/python/src/datastar_py/fastapi.py
  sdk/python/src/datastar_py/fasthtml.py
  sdk/python/src/datastar_py/quart.py
  sdk/python/src/datastar_py/responses.py
  sdk/python/src/datastar_py/sanic.py
  sdk/python/src/datastar_py/starlette.py
Labels: sdk

#756 Go SDK WithCompression option for NewSSE
  sdk/go/sse-compression.go
  sdk/go/sse.go
  sdk/go/types.go
Labels: sdk

#806 Add single/double asterisk wildcards
  CHANGELOG.md
  bundles/datastar-aliased.js
  bundles/datastar-aliased.js.map
  bundles/datastar.js
  bundles/datastar.js.map
  library/src/plugins/official/logic/actions/setAll.ts
  library/src/plugins/official/logic/actions/toggleAll.ts
  library/src/utils/paths.ts
  sdk/go/consts.go
  site/static/md/reference/action_plugins.md
  site/static/md/reference/attribute_plugins.md
  site/static/md/tests/on_signal_change_path_wildcard.md
  site/static/md/tests/set_all_path_wildcard.md
Labels: enhancement
